### PR TITLE
#167164969 Configure Authors Haven to use PostgreSQL as DB Engine

### PR DESCRIPTION
**Pull request by Ukhu**
#### Pivotal tracker story
[#167164969](https://www.pivotaltracker.com/story/show/167164969)

#### What does this PR do?
Sets up Sequelize as the ORM for the Postgres database

#### Summary of Task
  - remove files and folders not needed, and all mongoose set-up in the project
  - install sequelize, sequelize-cli, pg, and pg-hstore
  - create initial user model
  - create migrations for user model
  - create seeder for user model

#### How can this be tested?
```
clone this branch to your local repository

run npm install

add environment variables from the .env.sample file

run npm run db:ready to connect to the database by running the migrations and seeding the database

```

#### Screenshots (if appropriate)
Screenshot 2019-07-24 at 5 17 05 PM

### CODE REVIEW

**Review by WilliamsOhworuka — APPROVED** [review]

**Review by OvieMudi — APPROVED** [review]

**Review by Nerocodes — COMMENTED** [review]
Looks good. I noticed some es5 syntax in the database files that should be converted to es6, please review

**Review by OvieMudi — APPROVED** [review]

**Review by Nerocodes — APPROVED** [review]
Awesome! Great job.

**Comment by Ukhu** [comment]
> Looks good. I noticed some es5 syntax in the database files that should be converted to es6, please review

Thanks for the feedback. Some of those were auto-generated, but it's been fixed now.

**Review by allebd — COMMENTED** [review]
Your .env file should be added to the .gitignore file

**Comment by OvieMudi** [comment]
> Your .env file should be added to the .gitignore file

Yeah, nice catch!

**Pull request merged**
