### PR TITLE
#167942058 Get All Comments

### PR DESCRIPTION
**Pull request by allebd**
#### Pivotal tracker story
[#167942058](https://www.pivotaltracker.com/story/show/167942058)
#### What does this PR do?
Users should be able to see the number of likes for a comment
#### Summary of Task
- Create get comment controller
- Create a function to authorize users
- Add test
- Add swagger documentation
#### How can this be tested?
- Use **git clone** to clone this repository to local branch
- Use **npm install** to download all necessary packages
- Ensure your database is created or you can use **sequelize db:create** if database does not exist
- Use **npm run test**  to test
- Go your POSTMAN and type **http://localhost:${PORT}/api/v1/novels/:slug/comments** using a GET request to view a particular novel comments by slug
#### Screenshots (if appropriate)
Blank Diagram (3)
Flow Chart of Get all comments and like count

Screenshot 2019-08-20 at 4 28 00 AM
Screenshot of a successful request to get all comments

### CODE REVIEW

**Review by Rythae — APPROVED** [review]

**Review by Nerocodes — APPROVED** [review]
LGTM

**Comment by Nkemjiks** [comment]
Resolve merge conflicts @allebd

**Comment by allebd** [comment]
> Resolve merge conflicts @allebd

Working on it

**Review by WilliamsOhworuka — APPROVED** [review]

**Comment by allebd** [comment]
> > Resolve merge conflicts @allebd
> 
> Working on it

Conflicts have been resolved

**Pull request merged**
