### PR TITLE
#168108145 Get All Genres

### PR DESCRIPTION
**Pull request by allebd**
#### Pivotal tracker story
[#168108145](https://www.pivotaltracker.com/story/show/168108145)
#### What does this PR do?
Users should be able to view all genres
#### Summary of Task
- Create get genres controller
- Add test
- Add swagger documentation
#### How can this be tested?
- Use **git clone** to clone this repository to local branch
- Use **npm install** to download all necessary packages
- Ensure your database is created or you can use **sequelize db:create** if database does not exist
- Use **npm run test**  to test
- Go your POSTMAN and type **http://localhost:${PORT}/api/v1/genres** using a GET request to view all genres
#### Screenshots (if appropriate)
Blank Diagramooo

Flow Chart to Get all genres

Screenshot 2019-08-26 at 3 43 48 PM

Screenshot of a successful request to get all genres

### CODE REVIEW

**Comment by Nkemjiks** [comment]
Should i user be authenticated for them to get all genres @allebd ?

**Comment by allebd** [comment]
> Should i user be authenticated for them to get all genres @allebd ?


Yes, you would have to be logged in to get all genres, according to the PO

**Comment by Nkemjiks** [comment]
I think that should be included in the flow chart. Also fix the conflicts

**Comment by allebd** [comment]
> I think that should be included in the flow chart

Thank you for the observation, would work on it

**Comment by allebd** [comment]
> > I think that should be included in the flow chart
> 
> Thank you for the observation, would work on it

Treated accordingly

**Review by Rythae — APPROVED** [review]

**Pull request merged**
